name: Go

on:
  workflow_call:
    
jobs:
  docker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # username: ${{ secrets.DOCKERHUB_USER }} 
        # password: ${{ secrets.DOCKERHUB_PW }}
        username: reff20
        password: FPeres2013!!3003
