name: Docker

on:
  workflow_call:
    
jobs:
  docker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      env: 
        PW: ${{secrets.DOCKER_HUB_PW}}
        USER: ${{secrets.DOCKER_HUB_USER}}
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_HUB_USER}}
        password: ${{secrets.DOCKER_HUB_PW}}
